FROM ubuntu:18.04

LABEL version="0.1.0"
LABEL description="Docker image with base soft for developing: nano, mc, powershell, git, utils"

ENV ROOT_DIR=/root \
    DEV_DIR=dev \
    INST_DIR=install \
    DEBIAN_FRONTEND=noninteractive

WORKDIR $ROOT_DIR
RUN mkdir ./$INST_DIR
ADD ./ ./$INST_DIR/
RUN find ./$INST_DIR/ -name '*.sh' -exec chmod a+x {} +

RUN ./$INST_DIR/base_install.sh
ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'

RUN ls ./$INST_DIR

WORKDIR ${ROOT_DIR}/$DEV_DIR