FROM base-dev-env:0.1.0

LABEL version="0.1.0"
LABEL description="Docker image with base dev environment + xfce, tigervnc, vscode, chrome"

ENV VNC_PORT=5901 \
    VNC_PASSWD=ddockerr7 \
    VNC_DISPLAY=:1 \
    VNC_COL_DEPTH=24 \
    VNC_RESOLUTION=1920x1080 \
    OUTPUT=false

EXPOSE $VNC_PORT

WORKDIR $ROOT_DIR
ADD ./* ./$INST_DIR/
RUN find ./$INST_DIR/ -name '*.sh' -exec chmod a+x {} +

RUN ./$INST_DIR/tigervnc_install.sh
RUN ./$INST_DIR/vscode_install.sh
RUN ./$INST_DIR/chrome_install.sh
RUN ./$INST_DIR/xfce_install.sh
RUN ./$INST_DIR/post_install.sh

ADD ./xfce/ .

ENTRYPOINT ["/root/install/startup.sh"]
CMD ["/bin/bash"]