FROM base-dev-env:0.1.0

LABEL version="0.0.1"
LABEL description="Docker image with base dev environment + xfce, tigervnc, vscode, chrome"

WORKDIR $ROOT_DIR
ADD ./* ./$INST_DIR/
RUN find ./$INST_DIR/ -name '*.sh' -exec chmod a+x {} +

RUN ./$INST_DIR/tigervnc_install.sh
RUN ./$INST_DIR/chrome_install.sh
#RUN ./$INST_DIR/xfce_install.sh
RUN ./$INST_DIR/post_install.sh

WORKDIR ${ROOT_DIR}/$DEV_DIR